[package]
name = "mlir-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.12.1"
hashbrown = { version = "0.13.2", features = ["raw"] }
generational-arena = "0.2.8"
